#!/usr/bin/env python3
"""Generate 32×32 force field masks for nau_dx Amiga.

Output: C arrays for sweep (4 frames × src/dst) and bubble (4 frames).
Each row = 2 words (32 bits), 32 rows per mask.
"""

FW, FH = 32, 32
CX, CY = 15, 15
R = 14
RSQ = R * R

# Wipers for each frame (source = old pushed RIGHT → x >= wiper)
WIPERS = [2, 10, 19, 29]

def in_circle(x, y):
    dx = x - CX
    dy = y - CY
    return dx*dx + dy*dy <= RSQ

def mask_row_to_words(row_pixels):
    """Convert list of 32 ints (0/1) to two 16-bit hex words."""
    w0 = 0
    for bit in range(16):
        if row_pixels[bit]:
            w0 |= 1 << (15 - bit)
    w1 = 0
    for bit in range(16, 32):
        if row_pixels[bit]:
            w1 |= 1 << (31 - bit)
    return w0, w1

def gen_sweep(wiper_idx):
    """Generate src and dst masks for one sweep frame."""
    wiper = WIPERS[wiper_idx]
    src_pixels = []
    dst_pixels = []
    for y in range(FH):
        srow = []
        drow = []
        for x in range(FW):
            ci = in_circle(x, y)
            srow.append(1 if ci and x >= wiper else 0)
            drow.append(1 if ci and x < wiper else 0)
        src_pixels.append(srow)
        dst_pixels.append(drow)
    return src_pixels, dst_pixels

def gen_bubble(frame_idx):
    """Generate bubble mask for one frame.
    Pattern: 3 dense + 3 sparse rows, 6-row cycle.
    Each frame is shifted by `frame_idx` rows.
    """
    def is_dense(global_row):
        """Row within 6-cycle: first 3 dense, next 3 sparse."""
        cycle_pos = (global_row + frame_idx) % 6
        return cycle_pos < 3

    def sparse_pattern(x, global_row):
        """Checkerboard: depends on x parity (shifted each sparse row)."""
        cycle_pos = (global_row + frame_idx) % 6
        # Sparse rows are at positions 3,4,5 in the cycle
        # Use alternating pattern, shifted per row
        return (x + (cycle_pos - 3)) & 1

    pixels = []
    for y in range(FH):
        row = []
        dense = is_dense(y)
        for x in range(FW):
            if not in_circle(x, y):
                row.append(0)
            elif dense:
                row.append(1)
            else:
                row.append(1 if sparse_pattern(x, y) else 0)
        pixels.append(row)
    return pixels

def format_array(name, pixels_list):
    """Format a 2D pixel list as a C UWORD array."""
    lines = [f"static const UWORD {name}[FH*2] = {{"]
    for y, row in enumerate(pixels_list):
        w0, w1 = mask_row_to_words(row)
        comma = "" if y == FH - 1 else ","
        lines.append(f"    0x{w0:04X}, 0x{w1:04X}{comma}")
    lines.append("};")
    return "\n".join(lines)

def format_array_set(name_base, pixels_by_frame):
    lines = []
    for i, pix in enumerate(pixels_by_frame):
        lines.append(format_array(f"{name_base}{i}", pix))
    lines.append("")
    lines.append(f"static const UWORD* const {name_base}Set[4] = {{")
    for i in range(4):
        lines.append(f"    {name_base}{i},")
    lines.append("};")
    return "\n".join(lines)

# Generate all masks
print(f"// Auto-generated by tools/gen_forcefield.py — {FW}x{FH}, r={R}")
print(f"#define FH {FH}")
print(f"#define FW {FW}")
print()

# Sweep masks
all_src = []
all_dst = []
for i in range(4):
    src, dst = gen_sweep(i)
    all_src.append(src)
    all_dst.append(dst)
print(format_array_set("g_FFSweepSrc", all_src))
print()
print(format_array_set("g_FFSweepDst", all_dst))
print()

# Bubble masks
all_bub = []
for i in range(4):
    bub = gen_bubble(i)
    all_bub.append(bub)
print(format_array_set("g_FFBubScroll", all_bub))
