#!/usr/bin/env python3
"""
Reads the PNGs in shots/ and emits the corresponding C arrays for gfx.h.

--raw : read raw 4xN PNGs (e.g. shot_player_white_16.png) directly.
       Each pixel = 1 bit, no scaling grid.

Without --raw: read the 16xN scaled PNGs (white=body, red=accent, black=transparent)
       produced by shots_to_png.py.

Output is printed to stdout as C source you can paste into gfx.h.
"""
import os
import sys
from PIL import Image

SCALE = 16
SPRITE_W = 16
PAD = 12

def is_tx(r, g, b):
    return r < 20 and g < 20 and b < 20

def read_sprite(img_path, expected_h):
    img = Image.open(img_path).convert('RGB')
    w, h = img.size
    mask, body, accent = [], [], []
    for y in range(expected_h):
        non_tx = []
        for x in range(SPRITE_W):
            cx = PAD + x * SCALE + SCALE // 2
            cy = PAD + y * SCALE + SCALE // 2
            if cx < w and cy < h and not is_tx(*img.getpixel((cx, cy))):
                non_tx.append(x)
        if non_tx:
            x0, x1 = min(non_tx), max(non_tx)
        else:
            x0, x1 = -1, -1
        mw = bw = aw = 0
        for x in range(SPRITE_W):
            if x0 < 0 or x < x0 or x > x1:
                continue
            cx = PAD + x * SCALE + SCALE // 2
            cy = PAD + y * SCALE + SCALE // 2
            r, g, b = img.getpixel((cx, cy)) if cx < w and cy < h else (0,0,0)
            bit = 0x8000 >> x
            mw |= bit
            if is_tx(r, g, b):
                aw |= bit  # black inside mask = accent
            elif b > 200 and g > 180 and r < 20:
                bw |= bit  # blue = body
            elif r > 200 and g > 200 and b > 200:
                aw |= bit  # white = accent
            elif r > 200 and g < 80 and b < 80:
                bw |= bit  # red = body
            else:
                bw |= bit
        mask.append(mw); body.append(bw); accent.append(aw)
    return mask, body, accent

def read_raw_sprite(img_path, rows, polarity):
    img = Image.open(img_path).convert('RGB')
    w, h = img.size
    mask, body, accent = [], [], []
    for y in range(rows):
        non_tx = [x for x in range(w) if not is_tx(*img.getpixel((x, y)))]
        if non_tx:
            x0, x1 = min(non_tx), max(non_tx)
        else:
            x0, x1 = -1, -1
        mw = bw = aw = 0
        for x in range(w):
            if x0 < 0 or x < x0 or x > x1:
                continue
            bit = 0x8000 >> x
            mw |= bit
            r, g, b = img.getpixel((x, y))
            if is_tx(r, g, b):
                aw |= bit  # black inside mask = accent
            elif b > 200 and g > 180 and r < 20:
                bw |= bit  # blue = body
            elif r > 200 and g > 200 and b > 200:
                aw |= bit  # white = accent
            elif r > 200 and g < 80 and b < 80:
                bw |= bit  # red = body
            else:
                bw |= bit  # any other = body
        mask.append(mw); body.append(bw); accent.append(aw)
    return mask, body, accent

def is_tx(r, g, b):
    return r < 20 and g < 20 and b < 20

def fmt_array(values):
    parts = [f"0x{v:04X}" for v in values]
    lines = []
    for i in range(0, len(parts), 4):
        lines.append(", ".join(parts[i:i+4]))
    return ", ".join(parts)

SHOTS_DIR = os.path.join(os.path.dirname(__file__), "..", "shots")

def merge_sprite(name, white_fname, black_fname, expected_h):
    w_mask, w_body, _ = read_sprite(os.path.join(SHOTS_DIR, white_fname), expected_h)
    _, _, b_accent = read_sprite(os.path.join(SHOTS_DIR, black_fname), expected_h)
    body = [w_body[i] & ~b_accent[i] for i in range(len(w_body))]
    mask = [body[i] | b_accent[i] for i in range(len(body))]
    return mask, body, b_accent

def pad8(arr):
    while len(arr) < 8:
        arr.append(0)
    return arr

if __name__ == "__main__":
    raw = "--raw" in sys.argv
    print("// Auto-generated by tools/png_to_shots.py")
    if raw:
        print("// Raw mode: reads 4xN PNGs directly")
        print()
        for pname, fname, prefix, rows in [
            ("white", "shot_player_white_16.png", "g_Shot16W", 16),
            ("black", "shot_player_black_16.png", "g_Shot16B", 16),
        ]:
            mask, body, accent = read_raw_sprite(os.path.join(SHOTS_DIR, fname), rows, pname)
            print(f"static const UWORD {prefix}_Mask[{rows}]   = {{ {fmt_array(mask)} }};")
            print(f"static const UWORD {prefix}_Accent[{rows}] = {{ {fmt_array(accent)} }};")
            print(f"static const UWORD {prefix}_Body[{rows}]   = {{ {fmt_array(body)} }};")
            print()
    else:
        print("// body from _white.png -> dataLo -> BPL6 (dome), accent from _black.png -> dataHi -> BPL2 (white)")
        print("// body and accent NEVER overlap.")
        print()
        print("// --- PLAYER SHOT (4x8, 2-tone) ---")
        p_mask, p_body, p_accent = merge_sprite("player", "shot_player_white.png", "shot_player_black.png", 8)
        print(f"static const UWORD g_ShotMask[8]   = {{ {fmt_array(p_mask)} }};")
        print(f"static const UWORD g_ShotDataHi[8] = {{ {fmt_array(p_accent)} }};")
        print(f"static const UWORD g_ShotDataLo[8] = {{ {fmt_array(p_body)} }};")
        print()
        print("// --- ENEMY SHOT (10x4 diamond, 2-tone) ---")
        e_mask, e_body, e_accent = merge_sprite("enemy", "shot_enemy_white.png", "shot_enemy_black.png", 8)
        pad8(e_mask); pad8(e_body); pad8(e_accent)
        print(f"static const UWORD g_EShotMask[8]   = {{ {fmt_array(e_mask)} }};")
        print(f"static const UWORD g_EShotDataHi[8] = {{ {fmt_array(e_accent)} }};")
        print(f"static const UWORD g_EShotDataLo[8] = {{ {fmt_array(e_body)} }};")
